# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"3\n\x10UserDataResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63redit\x18\x02 \x01(\x05\"E\n\nTxnRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"7\n\x0cTxnIDRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\"#\n\x06Status\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32\xc7\x01\n\x0ePaymentService\x12\x37\n\x0f\x43heckoutPrepare\x12\x13.payment.TxnRequest\x1a\x0f.payment.Status\x12@\n\x0e\x43heckoutCommit\x12\x13.payment.TxnRequest\x1a\x19.payment.UserDataResponse\x12:\n\x10\x43heckoutRollback\x12\x15.payment.TxnIDRequest\x1a\x0f.payment.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDATARESPONSE']._serialized_start=26
  _globals['_USERDATARESPONSE']._serialized_end=77
  _globals['_TXNREQUEST']._serialized_start=79
  _globals['_TXNREQUEST']._serialized_end=148
  _globals['_TXNIDREQUEST']._serialized_start=150
  _globals['_TXNIDREQUEST']._serialized_end=205
  _globals['_STATUS']._serialized_start=207
  _globals['_STATUS']._serialized_end=242
  _globals['_PAYMENTSERVICE']._serialized_start=245
  _globals['_PAYMENTSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
