version: "3"

services:

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db-sentinel

  order-db-master:
    image: redis:7.2-bookworm
    hostname: order-db-master
    container_name: order-db-master
    volumes:
      - ./data/order-db/master:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6379",
        "--protected-mode", "no"
      ]

  order-db-slave:
    image: redis:7.2-bookworm
    container_name: order-db-slave
    hostname: order-db-slave
    depends_on:
      - order-db-master
    ports:
      - "6380:6379"
    volumes:
      - ./data/order-db/slave1:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--masterauth", "redis",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--replicaof", "order-db-master", "6379",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6380",
        "--protected-mode", "no"
      ]
  
  order-db-sentinel:
    image: redis:7.2-bookworm
    container_name: order-db-sentinel
    hostname: order-db-sentinel
    depends_on:
      - order-db-master
      - order-db-slave
    ports:
      - "26379:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor order-master order-db-master 6379 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass order-master redis" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds order-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout order-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs order-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
      
  # order-db:
  #   image: redis:7.2-bookworm
  #   command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db-sentinel

  stock-db-master:
    image: redis:7.2-bookworm
    hostname: stock-db-master
    container_name: stock-db-master
    volumes:
      - ./data/stock-db/master:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6380",
        "--protected-mode", "no"
      ]

  stock-db-slave:
    image: redis:7.2-bookworm
    container_name: stock-db-slave
    hostname: stock-db-slave
    depends_on:
      - stock-db-master
    ports:
      - "6381:6379"
    volumes:
      - ./data/stock-db/slave1:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--masterauth", "redis",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--replicaof", "stock-db-master", "6379",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6381",
        "--protected-mode", "no"
      ]
  
  stock-db-sentinel:
    image: redis:7.2-bookworm
    container_name: stock-db-sentinel
    hostname: stock-db-sentinel
    depends_on:
      - stock-db-master
      - stock-db-slave
    ports:
      - "26380:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor stock-master stock-db-master 6379 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass stock-master redis" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds stock-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout stock-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs stock-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db-sentinel

  payment-db-master:
    image: redis:7.2-bookworm
    hostname: payment-db-master
    container_name: payment-db-master
    volumes:
      - ./data/payment-db/master:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6381",
        "--protected-mode", "no"
      ]

  payment-db-slave:
    image: redis:7.2-bookworm
    container_name: payment-db-slave
    hostname: payment-db-slave
    depends_on:
      - payment-db-master
    ports:
      - "6382:6379"
    volumes:
      - ./data/payment-db/slave1:/data
    command:
      [
        "redis-server",
        "--appendonly", "yes",
        "--masterauth", "redis",
        "--requirepass", "redis",
        "--maxmemory", "512mb",
        "--replicaof", "payment-db-master", "6379",
        "--repl-diskless-load", "on-empty-db",
        "--replica-announce-port", "6382",
        "--protected-mode", "no"
      ]
  
  payment-db-sentinel:
    image: redis:7.2-bookworm
    container_name: payment-db-sentinel
    hostname: payment-db-sentinel
    depends_on:
      - payment-db-master
      - payment-db-slave
    ports:
      - "26381:26379"
    command: >
      sh -c 'echo "bind 0.0.0.0" > /etc/sentinel.conf &&
            echo "sentinel monitor payment-master payment-db-master 6379 1" >> /etc/sentinel.conf &&
            echo "sentinel auth-pass payment-master redis" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds payment-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout payment-master 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs payment-master 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
